# Generated by Django 3.1.2 on 2020-10-12 10:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishPicture',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('dish', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='picture', serialize=False, to='dishes.dish', verbose_name='Блюдо')),
                ('picture', models.ImageField(upload_to='dishes/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Изображение блюда',
                'verbose_name_plural': 'Изображения блюд',
            },
        ),
        migrations.RemoveField(
            model_name='dish',
            name='picture',
        ),
    ]
