version: "3.8"

services:
  django:
    command: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
    env_file: ./dev.env
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
    restart: unless-stopped

  nginx:
    command: echo
    restart: "no"

  postgres:
    env_file: ./dev.env
    restart: unless-stopped

  celery:
    command: ["celery", "--app", "restaurant_menu", "worker", "--loglevel", "DEBUG"]
    env_file: ./dev.env
    restart: unless-stopped

  redis:
    env_file: ./dev.env
    restart: unless-stopped